/**
 * @file orb_icons.h
 * Custom LVGL icon font (Material Design Icons subset) plus the UTF-8 symbol
 * macros for the glyphs it contains. The font itself is generated by
 * lv_font_conv into orb_icons.c (18 px, 4 bpp).
 *
 * A single LVGL label uses one font, and this icon font has no digits, so the
 * icons are placed in their own labels next to the Montserrat value labels.
 */
#pragma once

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

LV_FONT_DECLARE(orb_icons);

// UTF-8 encodings of the embedded Material Design Icons glyphs.
#define ORB_ICON_NOZZLE "\xF3\xB1\xA2\xB8"  // printer-3d-nozzle-heat (U+F18B8)
#define ORB_ICON_BED    "\xF3\xB0\x90\xB8"  // radiator              (U+F0438)
#define ORB_ICON_CLOCK  "\xF3\xB0\x85\x90"  // clock-outline         (U+F0150)
#define ORB_ICON_LAYERS "\xF3\xB0\xBD\x98"  // layers-triple         (U+F0F58)
